# Generated by Django 4.2.7 on 2025-08-27 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='modified',
            new_name='modified_at',
        ),
    ]
